### ISSUE TITLE
Namespace conflict between "pyserial" and "serial"

### ISSUE THREAD

**Issue by dstrigl** [toreamun/amshan#6]
You should remove "serial" from the requirements.txt, because "pyserial-asyncio" is based on "pyserial" and not "serial".

Otherwise the installation using "pip install -r requirements.txt" could end up in a namespace conflict between "pyserial" and "serial" like here: https://github.com/espressif/esptool/issues/269

This happened on my Raspberry Pi when installing your project using "pip install -r requirements.txt".
I got the error "... object has no attribute 'serial_for_url'", because it uses "serial" instead of "pyserial"
After removing "serial" from the requirements.txt and setting up the venv completely new (without "serial") it works!

Regards and thanks for your work on this,
Daniel.

**Comment by toreamun** [comment]
Thanks @dstrigl
